stackbit/jamstackthemes

content/theme/moltin-ecommerce-starter.md

Adds demo.moltin.com Gatsby demo store starter

Theme submission: Moltin ecommerce

---

content/theme/gatsby-theme-ultronele.md

New gatsby theme ultronele submitted.

Theme Submission: Ultronele

---

content/theme/hugo-theme-hermit.md

https://themes.gohugo.io/hermit/

Theme Submission: Hermit

---

content/theme/hugo-swift-theme.md
content/theme/newsroom.md

I have two Hugo themes that I actively maintain. I'm not sure if it's possible to submit more than one theme at once. Nonetheless, here they are:
1. Newsroom
2. Swift

Add Hugo Themes

---

content/theme/hitchens.md

Add Hitchens

---

content/theme/streamer-theme.md

I am submitting a theme called Streamer Theme

Theme Submission: Streamer Theme

---

content/theme/simpol-theme.md

adding [Simpol](https://github.com/scottmathson/simpol-theme), an open source Jekyll theme

adding simpol-theme

---

content/theme/garth.md

Added Garth for Jekyll

---

generate-github.js

Stale property is now part of the theme info objects in `data/thems.js` generated by the `generate-github.js` script. 
Closes #42

Added stale property for themes that are older than one year.

---

content/theme/colorie-jekyll.md
content/theme/gray-jekyll.md
content/theme/ultra-jekyll.md

Theme Submissions

---

content/theme/bael-theme.md

it looks like this is the first nuxt.js theme for your site?

add bael theme

---

content/theme/jekyll-theme-dark-reader.md
content/theme/jekyll-theme-milo.md

Added new theme  and updated author name & wrong date in my previous Milo Bootstrap theme

Theme Submission: Dark Reader

---

content/theme/hugo-primer-theme.md

Add Hugo-primer.
Hello, I found Hugo-primer already in content/.
However there is this `draft: true` param and my theme is not shown on your awesome site.
I assume it was automatic draft, so opened this issue.

Theme Submission: hugo-primer

---

content/theme/gridsome-airtable-starter.md

Submitting a Theme built with Gridsome and an Airtable Backend. 
Live Preview: [https://gridsomeairtable.netlify.com/](https://gridsomeairtable.netlify.com/)

Theme Submission: Gridsome Airtable Starter

---

content/theme/11tyframe.md

11tyframe request

---

content/theme/noir.md

Submission of the Noir theme for Jekyll websites.

Theme Submission: Noir

---

content/theme/jekyll-theme-retro-yellow.md

Theme Submission: Retro Yellow

---

content/themes/devlopr-jekyll.md

Theme Submission: devlopr-jekyll

---

content/theme/sidey-jekyll.md

Simple and minimalistic jekyll blogging theme

Theme Submission: Sidey

---

content/hyper.md

An unopinionated theme geared towards portfolios

Theme Submission: Hyper

---

content/ssg/eleventy/_index.md

Update Eleventy official URL

---

content/theme/jekyll-friday-theme.md

Here's a pull request for my submission to the themes directory, for my  own them 'Friday Theme', which I created for my personal web site at http://www.freytag.org.uk. I published the theme to GitHub and it has been sued by a few people since then, so I think it is reliable enough to be shared more widely. I look forward to your thoughts!

Added the Jekyll Friday Theme to the directory.

---

content/theme/gatsby-airtable-listing.md
content/theme/gatsby-contentful-portfolio.md

Submitting a new Gatsby starter. It's a portfolio-type website integrated with Contentful.
On-line demo is available at:
https://gatsby-contentful-portfolio.netlify.com/

Theme Submission: gatsby-contentful-portfolio & gatsby-airtable-listing

---

content/theme/rg-portfolio.md

Added new RG Portfolio jamstack theme

Theme Submission: RG Portfolio

---

content/theme/jekyll-neumorphism.md

Neumorphism designed Jekyll theme for personal websites, portfolios and resumes.
* [Repository](https://github.com/longpdo/neumorphism)
* [Demo](https://longpdo.github.io/neumorphism/)

Theme Submission: Neumorphism

---

content/theme/gatsby-theme-intro.md

Submitting a new Gatsby theme - personal website for developers.
On-line demo is available at:
https://weeby.studio/intro/preview/
Repository:
https://github.com/wkocjan/gatsby-theme-intro

Theme Submission: gatsby-theme-intro

---

content/theme/gatsby-starter-foundation.md

Adding `gatsby-starter-foundation`
Github: https://github.com/stackrole/gatsby-starter-foundation
Live Demo: https://foundation.stackrole.com/

Theme Submission: gatsby-starter-foundation

---

content/theme/11ty-starter-boilerplate.md

Little disclaimer: I am the author of the project. Recently, I have migrate my blog to Eleventy generator. So, I created a starter kit so the purpose and also hoping it could be useful for someone else.

Theme Submission: Eleventy Starter Boilerplate

---

content/theme/hugo-theme-iris.md

This pull request is ready to be merged. Could you confirm this?

Theme Submission: hugo-theme-iris

---

.gitignore
content/theme/gatsby-markdown-material-typescript-starter.md

Pulled some existing themes together to make something new.

Theme Submission: gatsby-markdown-material-typescript-starter

---

content/theme/jekyll-bay.md

Add post for Bay Jekyll theme.

Theme Submission: jekyll-bay

---

content/theme/dark-poole.md

Theme Submission: dark-poole

---

content/theme/nextjs-starter.md

A basic starter code for writing a blog on Nextjs framework that are based on React.

Add nextjs starter blog boilerplate

---

content/theme/hexo-webnary-template.md

New Hexo Theme Template Addition

Theme Submission: Web-Nary

---

content/theme/jekyll-lone-wolf-theme.md

Add `lone-wolf-theme` description to `content/theme` in `jamstackthemes` repo.

Theme submission: lone-wolf-theme

---

content/theme/vhealth-gatsby.md

Added [vHealth](https://vhealth.openthemes.dev) gatsby template
Thanks for creating jamstackthemes.dev :)

Theme Submission: vhealth-gatsby

---

content/theme/hugo-theme-line.md

Lines is a minimalistic Hugo blogging theme.

Added lines Hugo theme

---

content/theme/neat-starter.md

Added a new theme. 
(PS: It would be great if you could add #hacktoberfest tag in your project)

Add NEAT Starter Theme

---

content/theme/compose.md

* Update demo link
* Add one cms entry i.e forestry

Update compose theme info

---

content/theme/gatsby-nice-blog.md

GitHub URL: https://github.com/abhaynikam/gatsby-nice-blog
Demo URL: https://nostalgic-liskov-e76c32.netlify.app/
Screenshot:

Theme Submission: Nice Blog

---

content/theme/hexo-theme-minima.md

Theme Submission: Minima

---

content/theme/hugo-theme-zdoc.md
content/theme/hugo-theme-zzo.md

Theme Submission: Hugo theme Zzo, Hugo Theme Zdoc

---

content/theme/nextjs-simple-blog.md

I created this simple blog demo to show how to integrate Lyket with NextJS

Theme submission: NextJS simple blog + feedback buttons

---

content/theme/hugo-profile.md

Github link : [https://github.com/gurusabarish/hugo-profile](https://github.com/gurusabarish/hugo-profile)
Demo link: [https://hugo-profile.netlify.app/](https://hugo-profile.netlify.app)
Thanks,

hugo profile

---

content/theme/gatsby-starter-personal-portfolio

Thank you, @stackbithq team!
Github repo: https://github.com/gmlunesa/gatsby-starter-personal-portfolio
Demo: https://gatsby-starter-personal-portfolio.vercel.app/

Theme Submission: Gatsby Personal Portfolio

---

content/theme/jekyll-dumbarton.md

Adding my new Jekyll theme `Dumbarton`. The [submission guidelines](https://github.com/stackbithq/jamstackthemes) didn't mention which branch to make a PR too so I am using `master`.   
Theme Repo: https://github.com/tcbutler320/Jekyll-Theme-Dumbarton
Theme Demo: https://dumbarton.netlify.app/index.html

Theme Submission: Dumbarton

---

content/theme/hugo-papermod.md

Thank you for providing a nice platform to showcase themes :)

Theme Submission: PaperMod

---

content/theme/hugo-connectome.md

Hugo Connectome theme generates notes with backlinks and a graph of interconnected notes.

Add hugo connectome theme

---

content/theme/statiq-kontent-memoirs.md

Submission approved by @alanta

Theme Submission: statiq-kontent-memoirs

---

content/theme/gridsome-kontent-lumen.md

Submission approved by @ondrabus.

Theme Submission: gridsome-kontent-lumen

---

content/ssg/scully/_index.md
content/theme/scully-kontent-lumen.md
static/images/icons/scully.svg

Submission approved by @ondrabus.

Theme Submission: scully-kontent-lumen

---

content/ssg/sapper/_index.md
content/theme/sapper-kontent-cafe.md

+ Added Sapper to the SSG's taxonomy

Theme Submission: sapper-kontent-cafe

---

data/stackbit.json
scripts/build/stackbit.js

https://stackbit.slack.com/archives/CBURQFPLG/p1615472397001100
https://stackbit.slack.com/archives/C011E182KTK/p1614802735088400?thread_ts=1614793937.085600&cid=C011E182KTK

removed two create buttons from themes

---

content/theme/stackbit-ampersand-unibit.md
content/theme/stackbit-azimuth-unibit.md
content/theme/stackbit-diy-unibit.md
content/theme/stackbit-exto-unibit.md
content/theme/stackbit-fjord-unibit.md
content/theme/stackbit-fresh-unibit.md
content/theme/stackbit-libris-unibit.md
content/theme/stackbit-starter-unibit.md
content/theme/stackbit-vanilla-unibit.md

- updated stackbit theme repos to stackbit-themes

Hide-unibit

---

content/theme/next-static-neve.md

Added a Next.js theme based on Wordpress Neve theme which support posts & pages export.

add static neve theme

---

content/theme/11ty-landing-page.md
content/theme/hugo-landing-page.md

Thanks for this very cool project!
I've added a landing page theme I made, actually 2 Versions of it: one for Eleventy and one for Hugo.

Added a landing page theme I made

---

content/theme/hugo-showfolio.md

Demo: https://showfolio.vercel.app/

Add ShowFolio Theme for Hugo

---

content/theme/jekyll-enjoyment-work.md
content/theme/jekyll-purelog.md
content/theme/jekyll-watery.md

Hello! I have created three Jekyll themes and would like to submit them here! Thank you for your time.

Theme Submission: Watery, Purelog, and Enjoyment Work

---

content/theme/jekyll-bajawa.md

Bajawa, a minimalist jekyll theme with a touch of pastel colors.

Bajawa Jekyll Theme

---

content/theme/hugo-blist.md

Demo: https://blist.vercel.app/

Add Blist Theme for Hugo

---

content/cms/graphcms/_index.md
content/theme/graphcms-blog.md
content/theme/graphcms-commerce.md
content/theme/graphcms-marketing-website.md
static/images/icons/graphcms.svg

- Create a new CMS in `/content/cms` as `graphcms`
- Add icon for GraphCMS
- Add 3 OSS themes for GraphCMS (Blog, Commerce, Marketing Website)

Add graphcms

---

content/theme/minimal-bootstrap-blog.md

Add new theme minimal-bootstrap-blog

---

content/theme/11ty-soft-ui-design.md

Eleventy Soft UI is an Eleventy adaptation of Soft UI Design System (a user-friendly and beautiful design system based on Bootstrap 5), including a Blog system that uses Prismic CMS for content management.

Eleventy Soft UI Design - New JAMstack starter

---

content/theme/11straps.md

Correct theme typo

---

content/theme/hugo-book.md

Hi!
URL for demo site udpated for hugo-book theme

Update hugo-book theme demo URL

---

content/theme/urban.md

Hi there,
really awesome dictionary of themes!
I would like to contribute mine, too :)
Have a nice week
midzer

Add urban theme

---

content/theme/hugo-digital-garden.md

Demo: https://digital-garden-hugo-theme.vercel.app/

Add Hugo Digital Garden theme

---

content/theme/jekyll-h2o-ac.md

Add a new Jekyll theme named `H2O-ac`. 
Please check it. 
Thank you very much.

Add jekyll-h2o-ac

---

content/theme/hugo-anatole.md

This PR adds the Anatole theme for Hugo SSG.
Thank you very much!

Add Anatole Theme for Hugo

---

content/theme/hugo-theme-scroll.md

github: https://github.com/janraasch/hugo-scroll
demo: https://janraasch.github.io/hugo-scroll/
This theme is already indexed on themes.gohugo.io, but was missing here.
Thanks!

[theme] Add Hugo Scroll

---

content/theme/gatsby-theme-serial-programmer.md
content/theme/hugo-theme-serial-programmer.md
content/theme/jekyll-theme-serial-programmer.md

Opening PR again because Something happened in the last one, Gatsby theme didn't showed up.

Add Serial Programmer for Jekyll, Hugo & Gatsby

---

content/theme/bilberry-hugo-theme.md
content/theme/gohugo-theme-ananke.md
content/theme/hugo-papermod.md

Themes: fix some links and update descriptions

---

content/theme/hugo-congo.md

Updating the theme details after a recent major update

Update Hugo Congo theme details

---

content/theme/hugo-academia.md
content/theme/hugo-airspace.md
content/theme/hugo-andromeda.md
content/theme/hugo-apollo.md
content/theme/hugo-bigspring.md
content/theme/hugo-bookworm.md
content/theme/hugo-dot.md
content/theme/hugo-educenter.md
content/theme/hugo-geeky.md
content/theme/hugo-hargo.md
content/theme/hugo-infinity.md
content/theme/hugo-influencer.md
content/theme/hugo-kross.md
content/theme/hugo-liva.md
content/theme/hugo-meghna.md
content/theme/hugo-navigator.md
content/theme/hugo-omega.md
content/theme/hugo-parsa.md
content/theme/hugo-persian.md
content/theme/hugo-restaurant.md
content/theme/hugo-techfeed.md
content/theme/hugo-timer.md
content/theme/hugo-touchy.md
content/theme/hugo-twenty-twenty.md
content/theme/hugo-vex.md

Hello there,
We have updated our demo links for all Hugo themes, so we need to update the links here too. This PR will update all the themes demo links. thank you. Have a good day

update all themefisher, gethugo, statichunt theme demo links

---

content/theme/next-ecommerce.md
content/theme/next-react-storefront.md

nextjs ecommerce theme

---

content/theme/Xtreme-free-nextjs-admin.md

Submitted Xtreme Next Js Free Admin Template

 Xtreme-free-nextjs-admin

---

content/theme/nextacular.md

Nextacular

---

content/theme/nuxt-tailwind-blog-starter.md

This theme is based on NuxtJS with tailwind css & supported Markdown for blog.

Upload nuxt-tailwind-blog-starter

---

content/theme/jekyll-mr-green.md

demo link updated

---

content/theme/hugo-theme-dopetrope.md
content/theme/hugo-theme-massively.md

Updates the github repo references of two themes which I am the author of

Update Hugo theme github repo references

---

content/theme/react-portfolio-template.md

Live - https://react-portfolio-template.netlify.app/
Demo Video - https://www.youtube.com/watch?v=62_HLbx2zLQ&t=9s
Tutorials
Youtube - https://www.youtube.com/watch?v=8cmJ2kR4SpM
Blog - https://blog.chetanverma.com/how-to-build-a-portfolio-website-using-nextjs-and-tailwindcss

React Portfolio Template

---

content/theme/maverick.md

Add Maverick theme to the list

Add Maverick to theme lists

---

content/theme/11ty-docs.md

Lots of customers of [Spinal](https://spinalcms.com/) use 11ty. 😎 
Checkout a preview of this theme here: https://11ty-docs-theme.spinalcms.com/

Added 11ty docs theme

---

content/theme/hugo-flex.md

Restore the Hugo Flex theme which was disabled due to a broken demo link.

Restore Hugo Flex

---

content/theme/chulapa.md

Thanks for the site! I would like to add my Jekyll Theme
Thanks

Add Chulapa Theme

---

content/theme/eleventy-satisfactory.md

Hi there, adding a new theme for Eleventy.

Add Eleventy Satisfactory theme

---

content/theme/hugo-theme-scroll.md

Updated reference to Hugo Scroll theme after transfer new owner

Update hugo-theme-scroll.md after repository transfer

---

content/theme/hugo-texify2.md

Add [texify2](https://github.com/weastur/hugo-texify2) hugo theme

Add texify2 hugo theme

---

content/theme/hugo-xterm.md
content/theme/jekyll-lone-wolf-theme.md

Add hugo-xterm to `content/theme`.

Theme submission: hugo-xterm

---

content/theme/hugo-theme-docura.md

A modular Hugo theme to build your next documentation site.
- title: Docura
- github: https://github.com/docura/docura
- demo: https://docura.github.io
- ssg: Hugo
**Features**
- Responsive and adaptive layouts.
- Built-in dark, light and night themes.
- Customizable menu with Hugo configs.
- Customizable sidebars using Hugo data templates.
- Support for multiple documentation sets.
- Minimal reliance on external frameworks (No CSS, JS/npm, icon, font frameworks).
- SCSS/Vanilla JS based UI components and Hugo pipes based building process.

Add Docura Hugo Theme

---

content/theme/hugo-dot-org-theme.md

Add Dot-Org Theme

---

content/theme/hugo-blog-awesome.md

This theme (Hugo blog awesome) was disabled since the demo url was not found.
I have fixed it with this PR.
https://github.com/hugo-sid/hugo-blog-awesome
https://hba.sid.one/

Update Hugo blog awesome

---

content/theme/astro-landing-page.md

Adding my Astro landing page template.

Add: astro-landing-page.md

---

content/theme/jekyll-nagymaros.md

I just noticed I left the title from another theme. Sorry!

Fix mistake in heading

---

content/theme/ovidius-astro-theme.md

Added new Ovidius Astro.js theme.

added ovidius-astro-theme.md

---

content/theme/Materio Free Vuetify NuxtJS Admin Template

Materio Free Vuetify Nuxtjs Admin Template is the most developer-friendly & highly customizable template based on VueJS. Besides, it is available in both Typescript and JavaScript versions.
If you’re a developer looking for a NuxtJS Admin Template that is developer-friendly, rich with features, and highly customizable, look no further than the Materio Vuetify NuxtJS admin template.
Link: https://github.com/themeselection/materio-vuetify-nuxtjs-admin-template-free
Demo: https://demos.themeselection.com/materio-vuetify-nuxtjs-admin-template-free/demo/dashboard

Added Materio Free Vuetify NuxtJS Admin Template

---

content/ssg/zola/_index.md
static/images/icons/zola.svg

feat: add zola ssg

---

content/theme/jekyll-theme-satellite.md

**Satellite🛰️ - Jekyll blog theme**
An emotional and adorable blog theme powered by Jekyll.
* Comment System using *giscus*
* Copy contents of Code Block
* Dark/Light Theme
* Google Analytics
* Hierarchical Categorization
* Mobile friendly design
* Related Posts
* RSS/Sitemap support
* Search Post by Title or Tags
* Syntax Highlighter (*highlight.js*)
* Table of Contents
* Visitor Counter (*goatcounter*)

Submit a theme: jekyll-theme-satellite

---

content/theme/hugo-flex.md

Update the Hugo Flex theme to add the latest features and fix the broken links.

Update Hugo Flex

---

content/theme/hugo-poison.md

Adding Hugo Poison theme

---

content/theme/yanbt.md

Also was wondering if https://nuxt.studio/ qualifies as CMS it's git based and new.
Thank You!

Add yanbt blog theme

---

content/theme/jekyll-professional-resume.md

**🎓 - Jekyll Professional Resume**
A simple and modern resume template, best fit for either Academic CV (Curriculum Vitae) or Engineer Portfolio.
github repo: https://github.com/byanko55/jekyll-professional-resume

Submit theme: jekyll-professional-resume

---

content/theme/gatsby-blog-revista.md

Updated Revista URL as I am migrating away from Netlify

Update Revista url

---

content/theme/awesome-jekyll-theme

Create awesome-jekyll-theme.md file

---

content/theme/hugo-theme-yue.md

Fix https://github.com/stackbit/jamstackthemes/pull/505#issuecomment-2306576147 .

fix filename of hugo-theme-yue

---

content/theme/astro-astromax.md
content/theme/astro-astrosaas.md
content/theme/astro-microblog.md
content/theme/astro-swissfolio.md

Corrected new links for the Open Source templates on Michael Andreuzza name

new links on templates
